-- V4__vet_knowledge.sql (H2-compatible)
-- Veterinary knowledge base - simplified for H2 (no TSVECTOR support)

CREATE TABLE vet_knowledge (
    id            BIGINT AUTO_INCREMENT PRIMARY KEY,
    category      VARCHAR(100) NOT NULL,
    pet_type      VARCHAR(50),
    title         VARCHAR(300) NOT NULL,
    content       TEXT NOT NULL,
    search_vector VARCHAR(1) DEFAULT NULL
);

CREATE INDEX idx_vet_knowledge_category ON vet_knowledge (category);
CREATE INDEX idx_vet_knowledge_pet_type ON vet_knowledge (pet_type);

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Dog', 'Common Health Issues in Dogs',
'Dogs are susceptible to a range of health conditions that owners should watch for. Skin allergies are among the most frequent complaints, presenting as excessive scratching, hot spots, or recurring ear infections. Dental disease affects the majority of dogs over age three and can lead to pain, tooth loss, and systemic infection if untreated. Obesity is another prevalent problem; even modest excess weight accelerates joint wear and increases risk of diabetes and heart disease. Gastrointestinal upsets — vomiting, diarrhea, or sudden changes in appetite — are common and often self-limiting but warrant veterinary attention if they persist beyond 24 to 48 hours or are accompanied by blood. Respiratory infections such as kennel cough spread rapidly in social settings and cause a characteristic honking cough. Parvovirus remains a serious threat in unvaccinated or partially vaccinated puppies, causing profuse bloody diarrhea and rapid dehydration. Urinary tract infections, particularly in female dogs, often manifest as increased urgency, straining, or blood-tinged urine. Arthritis in senior dogs leads to stiffness, reluctance to climb stairs, and a shortened stride. Annual wellness exams allow early detection of many conditions before clinical signs become severe.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Cat', 'Common Health Issues in Cats',
'Cats are masters at hiding illness, making routine veterinary care essential. Upper respiratory infections caused by feline herpesvirus or calicivirus are widespread, especially in multi-cat households and shelters, producing sneezing, nasal discharge, and conjunctivitis. Dental disease is nearly universal in cats by age five; gingivitis and tooth resorption cause chronic pain that owners may not notice until the cat stops eating. Feline lower urinary tract disease (FLUTD) encompasses a spectrum of conditions including bladder inflammation, crystals, and urethral obstruction — the last being a life-threatening emergency in male cats presenting as inability to urinate. Hyperthyroidism, the most common endocrine disorder in older cats, causes weight loss despite a ravenous appetite, restlessness, and elevated heart rate. Chronic kidney disease is extremely common in cats over ten years old and progresses silently until significant function is lost. Feline diabetes presents with increased thirst, urination, and weight loss despite good appetite. Parasites such as ear mites, fleas, and intestinal worms remain common even in indoor cats. Regular blood panels from age seven onward help catch kidney disease, hyperthyroidism, and diabetes at treatable stages.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Rabbit', 'Common Health Issues in Rabbits',
'Rabbits have a delicate digestive system that requires constant movement of gut contents. Gastrointestinal stasis — a slowdown or cessation of gut motility — is one of the most dangerous conditions in rabbits and can be fatal within 24 to 48 hours if untreated. Signs include reduced or absent fecal pellets, loss of appetite, and a hunched posture. Dental disease is equally important; rabbit teeth grow continuously and misalignment leads to spurs that lacerate the tongue and cheeks, causing pain and anorexia. Uterine cancer (uterine adenocarcinoma) affects unneutered female rabbits at high rates — spaying before two years of age is strongly recommended. Ear mites (Psoroptes cuniculi) cause intense irritation and a thick, crusty discharge inside the ear. Encephalitozoon cuniculi is a microsporidial parasite that can cause head tilt, hind-limb paresis, and urinary incontinence. Respiratory infections with Pasteurella multocida (snuffles) produce chronic nasal discharge and can spread to the ears, eyes, or lungs. Rabbits are obligate nasal breathers, so any nasal obstruction is immediately serious. A diet of predominantly fresh hay (80% of intake), supplemented with leafy greens and limited pellets, is the cornerstone of rabbit health.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Guinea Pig', 'Common Health Issues in Guinea Pigs',
'Guinea pigs are social, sensitive animals prone to several specific health conditions. Scurvy is unique to guinea pigs among common pets because, like humans, they cannot synthesize vitamin C endogenously. Deficiency causes lethargy, rough coat, swollen painful joints, and poor wound healing; it is prevented by providing 10–30 mg of vitamin C daily through fresh bell peppers, leafy greens, or supplemented water. Respiratory infections are common and can progress rapidly; signs include labored breathing, nasal discharge, and hunched posture. Upper respiratory disease is often caused by Bordetella bronchiseptica, which can be transmitted from dogs, cats, or rabbits sharing a household. Dental malocclusion and cheek tooth overgrowth (slobbers) cause drooling, weight loss, and inability to chew, requiring veterinary dental work under anesthesia. Mites (Trixacarus caviae) cause intense pruritus, hair loss, and in severe cases, seizures. Urinary stones — calcium oxalate or calcium carbonate — cause straining, hematuria, and are often associated with high-calcium diets. Ovarian cysts are common in intact females over two years and cause bilateral flank hair loss and behavioral changes. Regular handling helps owners detect lumps, weight changes, and abnormal posture early.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Bird', 'Common Health Issues in Pet Birds',
'Pet birds, including parrots, cockatiels, and canaries, mask illness instinctively as a survival mechanism. By the time obvious signs appear, a bird is often severely ill. Key warning signs include fluffed feathers while awake, tail bobbing (indicating labored breathing), discharge from nares or eyes, changes in droppings color or consistency, and sudden weight loss. Psittacosis (Chlamydiosis) caused by Chlamydia psittaci is a zoonotic bacterial infection presenting as respiratory distress, lethargy, and lime-green diarrhea; it requires prompt antibiotic treatment. Proventricular Dilatation Disease (PDD), caused by a bornavirus, affects the digestive nervous system, causing regurgitation, undigested seeds in droppings, and progressive wasting. Aspergillosis is a serious fungal infection of the respiratory tract, particularly in immunocompromised birds kept in poorly ventilated or damp environments. Feather destructive behavior (feather plucking) has numerous causes including psychological stress, infection, nutritional deficiency, or endocrine disorders and should be evaluated by an avian veterinarian. Heavy metal toxicosis from zinc or lead in cage materials causes neurological signs, regurgitation, and polyuria. Annual wellness exams, including weigh-ins and fecal analysis, are important for all pet birds.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Hamster', 'Common Health Issues in Hamsters',
'Hamsters have a short lifespan of two to three years and are prone to several conditions that require prompt veterinary attention. Wet tail (proliferative ileitis) is the most serious illness in hamsters, caused by Lawsonia intracellularis infection triggered by stress. It produces severe, foul-smelling diarrhea, a wet, matted tail area, lethargy, and hunched posture. Without treatment within 24 to 48 hours, wet tail is often fatal. Respiratory infections present as wheezing, nasal discharge, and labored breathing, frequently caused by cold drafts or bacteria. Dental problems including overgrown incisors prevent eating and require trimming. Cheek pouch impaction occurs when sticky foods lodge in the pouches, causing swelling and inability to empty them, requiring veterinary removal. Hibernation torpor can be mistaken for death in cold environments; warm the hamster gently and seek veterinary care if it does not revive within minutes. Diabetes is common in Campbell dwarf hamsters, presenting with polyuria and polydipsia. Skin conditions including ringworm (fungal infection) and mite infestation cause hair loss and itching. Tumors, both benign and malignant, are unfortunately common in hamsters over 18 months old, particularly flank organ tumors and melanomas.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Turtle', 'Common Health Issues in Turtles',
'Turtles and tortoises are long-lived reptiles with specific environmental and dietary needs that, when unmet, lead to predictable health problems. Metabolic Bone Disease (MBD) is the most prevalent nutritional disorder, caused by insufficient UVB lighting or dietary calcium, leading to a soft, deformed shell, fractures, and muscle weakness. Shell rot (ulcerative shell disease) is a bacterial or fungal infection of the shell presenting as pitting, discoloration, foul odor, and soft areas; it requires debridement and antimicrobial treatment. Respiratory infections cause open-mouth breathing, wheezing, mucus discharge from the nares, and listing to one side when swimming in aquatic species. Vitamin A deficiency is common in turtles fed exclusively commercial pellets without leafy greens; it causes swollen eyelids (aural abscesses in box turtles), nasal discharge, and poor skin quality. Parasitic infections with roundworms, flagellates, and coccidia are common in wild-caught or poorly managed turtles and cause diarrhea and wasting. Egg binding (dystocia) affects female turtles if appropriate nesting substrate is unavailable. Proper husbandry — correct temperatures, full-spectrum UVB lighting, and a varied diet — prevents the majority of turtle health problems.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Snake', 'Common Health Issues in Snakes',
'Snakes are obligate carnivores and ectotherms whose health is fundamentally tied to their husbandry. Respiratory infections are among the most common conditions, presenting as wheezing, open-mouth breathing, mucus accumulation in the mouth, and lethargy; they are often secondary to inadequate thermal gradients or humidity. Inclusion Body Disease (IBD) is a fatal viral disease affecting boid snakes (boas and pythons), causing neurological signs such as stargazing, loss of righting reflex, and regurgitation; it is contagious and incurable. Mites (Ophionyssus natricis) cause restlessness, anorexia, and dull skin; small dark dots may be visible moving on the snake or soaking water. Scale rot (necrotic dermatitis) results from sustained contact with damp substrate and bacteria, causing blistered or discolored scales. Dysecdysis — incomplete or retained shed — is caused by low humidity or parasitism and can lead to retained eye caps (spectacles) that damage vision. Stomatitis (mouth rot) is a bacterial infection of the oral cavity presenting as swollen gums, caseous exudate, and reluctance to eat. Regurgitation may be caused by overhandling after feeding, incorrect temperatures, infection, or foreign body obstruction. Annual fecal exams detect parasitic infections before they cause weight loss.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', NULL, 'When to Seek Emergency Veterinary Care',
'Certain clinical signs in any pet constitute an emergency requiring immediate veterinary attention, regardless of species. Difficulty breathing, open-mouth breathing in cats or birds, labored or rapid respiration, or any bluish tinge to gums or mucous membranes signals oxygen compromise and is always an emergency. Inability to urinate or defecate, especially in male cats or any rabbit, can be fatal within hours. Collapse, unresponsiveness, or inability to stand requires urgent care. Profuse or uncontrolled bleeding that does not stop with direct pressure within five minutes needs immediate attention. Suspected ingestion of a toxin — whether a plant, medication, cleaning product, or known animal poison — warrants a call to a pet poison hotline and often an emergency visit even if the animal appears normal, as some toxins have delayed effects. Seizures lasting more than two to three minutes, or multiple seizures in a day, are medical emergencies. Pale, white, or gray gums indicate shock or severe anemia. Swollen, distended abdomen, especially in large breed dogs, may indicate life-threatening gastric dilatation-volvulus (GDV). Eye injuries or sudden vision loss need same-day evaluation. When in doubt, call your veterinary clinic — most practices and emergency centers offer phone triage to help determine urgency.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', NULL, 'Preventive Care: Annual Wellness Exams',
'Annual wellness examinations form the foundation of preventive veterinary care. During a wellness exam, the veterinarian performs a thorough physical assessment including evaluation of body weight and condition score, lymph nodes, teeth and gums, eyes, ears, skin and coat, heart and lung sounds, abdominal palpation, and musculoskeletal condition. For puppies and kittens, wellness visits also include vaccination series and parasite screening. Starting at middle age (typically seven years for dogs and cats, though this varies by species and breed), blood panels and urinalysis help detect metabolic diseases, organ dysfunction, and endocrine disorders at subclinical stages when treatment is most effective. Fecal parasite exams are recommended at least annually for dogs and cats with outdoor access, and for most exotic species. Dental prophylaxis under anesthesia is often recommended annually or every one to two years, as periodontal disease is the most common disease in companion animals. Weight monitoring at each visit allows early intervention for obesity or unexpected weight loss, both of which signal health problems. Preventive care is consistently more cost-effective than treating advanced disease and significantly improves quality and length of life.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Dog', 'Canine Parvovirus: Recognition and Prevention',
'Canine parvovirus (CPV-2) is one of the most devastating infectious diseases of dogs, particularly affecting puppies between six weeks and six months of age. The virus attacks rapidly dividing cells, primarily the intestinal epithelium and bone marrow, causing hemorrhagic gastroenteritis and immune suppression. Clinical signs begin with lethargy and anorexia, progressing rapidly to profuse vomiting, foul-smelling bloody diarrhea, dehydration, and fever — though hypothermia may occur in severe cases. The virus is environmentally hardy, surviving months on surfaces and resistant to many common disinfectants; bleach at 1:32 dilution is effective. Transmission occurs through direct contact with infected feces or contaminated environments. Mortality without treatment is 90%; with aggressive inpatient supportive care including IV fluids, anti-nausea medication, antibiotics to prevent secondary infection, and nutritional support, survival rates reach 70 to 90%. Vaccination is highly effective; puppies receive a series of vaccines starting at 6 to 8 weeks and repeated every three to four weeks until 16 weeks old. Unvaccinated or incompletely vaccinated puppies should avoid dog parks, pet stores, and areas with unknown vaccination status until the series is complete. Annual or triennial boosters maintain immunity in adult dogs.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('general_health', 'Cat', 'Feline Hyperthyroidism: Signs and Management',
'Hyperthyroidism is the most common endocrine disorder in cats, predominantly affecting cats over 10 years of age, and is caused by benign enlargement of one or both thyroid glands producing excess thyroid hormone. The elevated metabolic rate causes a characteristic combination of weight loss despite markedly increased appetite, hyperactivity or restlessness, vocalization especially at night, unkempt coat, vomiting, and diarrhea. The increased cardiac output leads to hypertrophic cardiomyopathy, elevated blood pressure, and — if untreated — retinal detachment, kidney damage, and heart failure. Diagnosis is confirmed by measuring serum total T4, which is elevated in most affected cats. Treatment options include daily oral methimazole (or transdermal gel applied to the inner ear flap), surgical thyroidectomy, radioactive iodine (I-131, the gold standard curative treatment), or prescription iodine-restricted diets (Hill''s y/d). Methimazole requires regular blood monitoring for bone marrow suppression and kidney function — hyperthyroidism can mask concurrent kidney disease, which may emerge after treatment reduces the elevated blood flow. Radioactive iodine is curative in over 95% of cases with a single treatment and no long-term medication. Regular thyroid palpation during wellness exams facilitates early detection.');

-- ============================================================
-- CATEGORY: nutrition
-- ============================================================

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Dog', 'Canine Nutrition Basics: Life Stage Feeding',
'Dogs have different nutritional requirements at each life stage and should be fed diets formulated accordingly. Puppies need higher protein (22–32%), fat (8–20%), and calcium for growth; large breed puppies require controlled calcium and phosphorus levels to prevent developmental orthopedic disease — avoid generic puppy foods for breeds expected to exceed 50 pounds at maturity. Adult maintenance diets should meet AAFCO nutrient profiles and be matched to the dog''s activity level and body condition score; most adult dogs do well on twice-daily feeding rather than free-choice. Senior dogs (over seven years, or five for giant breeds) benefit from diets with adjusted caloric density, enhanced omega-3 fatty acids for joint and cognitive support, and often controlled phosphorus for kidney health. Transition between diets over seven to ten days by gradually mixing the new food in increasing proportions to avoid gastrointestinal upset. Body condition scoring (1–9 scale) at each meal preparation helps owners detect gradual weight change; ribs should be easily felt but not visually prominent. Treats should not exceed 10% of daily caloric intake. Always provide fresh water; water intake is a useful health indicator and changes warrant investigation.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Dog', 'Toxic Foods for Dogs',
'Several common human foods are toxic to dogs and should be completely avoided. Grapes and raisins (including currents) cause acute kidney failure in some dogs; the toxic dose is variable and even small amounts have caused death — the mechanism is not fully understood, making no "safe" amount. Chocolate contains theobromine and caffeine, both methylxanthines that dogs metabolize slowly; dark chocolate and baking chocolate are most dangerous, causing vomiting, diarrhea, agitation, muscle tremors, seizures, and cardiac arrhythmias. The toxic dose for milk chocolate is roughly 1 oz per pound of body weight, but dark chocolate is toxic at 0.1 oz per pound. Xylitol (birch sugar), found in sugar-free gum, candies, some peanut butters, and baked goods, causes profound hypoglycemia within 30–60 minutes and delayed hepatic necrosis. Onions, garlic, leeks, and chives — cooked, raw, or powdered — cause oxidative damage to red blood cells, leading to hemolytic anemia; garlic is approximately five times more toxic than onions. Macadamia nuts cause weakness, hyperthermia, vomiting, and tremors. Avocado (persin) causes vomiting and diarrhea. Alcohol and caffeine are toxic even in small amounts. If ingestion is suspected, contact a veterinarian or pet poison control hotline (ASPCA: 888-426-4435) immediately.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Cat', 'Toxic Foods for Cats',
'Cats have unique metabolic limitations that make certain foods lethal to them. Lilies of the Lilium and Hemerocallis genera (Easter lily, tiger lily, daylily, stargazer) are extremely toxic to cats — ingestion of even a few petals or leaves causes acute kidney failure, and water from a vase containing lilies has caused fatal toxicity. All parts of the lily plant are dangerous. Onions, garlic, chives, and leeks damage feline red blood cells and cause hemolytic anemia; cats are more susceptible than dogs. Grapes and raisins can cause kidney failure in cats, though reports are less common. Alcohol is rapidly absorbed and causes dose-dependent respiratory depression and hypoglycemia. Xylitol causes less dramatic hypoglycemia in cats than in dogs but is still harmful. Raw fish and liver in large quantities cause thiamine deficiency (raw fish contains thiaminase) and vitamin A toxicity respectively. Chocolate is toxic due to theobromine, though cats rarely ingest it voluntarily. Tuna in large amounts leads to steatitis (yellow fat disease) from vitamin E deficiency and excessive mercury exposure. Dairy products — contrary to popular belief — cause gastrointestinal upset in most adult cats due to lactose intolerance. Caffeinated beverages cause rapid heart rate, tremors, and collapse.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Cat', 'Feline Nutrition: Why Cats Need Meat',
'Cats are obligate carnivores, meaning they require nutrients found exclusively in animal tissue that other mammals can synthesize. Taurine, an amino acid critical for cardiac function, retinal health, and fetal development, is found almost exclusively in meat; dietary deficiency causes dilated cardiomyopathy, blindness, and reproductive failure. Unlike dogs, cats cannot convert linoleic acid to arachidonic acid and must obtain this long-chain fatty acid from animal fat. Cats also cannot produce sufficient niacin from tryptophan, vitamin D from sun exposure, or vitamin A from beta-carotene — all must be supplied in the diet through animal-sourced ingredients. High-quality commercial cat foods meet these requirements; vegetarian or vegan diets are inappropriate for cats without careful supplementation. Cats are natural prey-eaters and thrive on high-protein (30–45% DM), moderate-fat, low-carbohydrate diets; excess dietary carbohydrate contributes to obesity and diabetes. Wet food provides significant moisture, supporting kidney function and reducing the risk of urinary crystals; cats that eat only dry food often have chronically low-grade dehydration. Puzzle feeders and multiple small meals mimic natural hunting behavior and reduce stress-related overeating. Life-stage formulation is important; kitten food provides higher caloric density and nutrient levels for growth.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Rabbit', 'Rabbit Diet: The Importance of Hay',
'A proper rabbit diet is dominated by high-quality grass hay, which should constitute 80 to 90 percent of daily intake for both adults and young rabbits. Timothy hay, orchard grass, and meadow hay are excellent choices for adult rabbits; oat hay and alfalfa are appropriate for young rabbits under six months old but too high in calcium and protein for adults. Hay provides the critical indigestible fiber that maintains gut motility, wears down continuously growing teeth, and supports the cecotrope production that delivers essential nutrients. A rabbit who stops eating hay is at immediate risk of GI stasis. Fresh leafy greens — romaine lettuce, bok choy, cilantro, parsley, kale, and herbs — should be offered daily, approximately one packed cup per two pounds of body weight. Pellets should be plain (no seeds, dried fruit, or colored pieces), timothy-based, and limited to about one-quarter cup per five pounds daily for adults; excessive pellets cause obesity and discourage hay consumption. Fruit should be a rare treat only — one to two tablespoons of low-sugar fruit such as apple or strawberry per week. Cabbage, iceberg lettuce, and spinach (in large quantities) cause digestive upset. Fresh water must be available at all times, preferably in both a bowl and a bottle.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Guinea Pig', 'Guinea Pig Nutrition: Vitamin C and a Balanced Diet',
'Guinea pigs cannot synthesize vitamin C and must obtain adequate amounts through diet daily, as the vitamin is not stored long-term. Deficiency leads to scurvy within two to four weeks, causing lethargy, rough coat, swollen joints, bleeding gums, slow wound healing, and reluctance to move. Red bell pepper is the most reliable and palatable source, providing approximately 140 mg per 100 g. Other good sources include kale, parsley, cilantro, dandelion greens, and strawberries. Vitamin C in commercial pellets degrades rapidly — often within 90 days of manufacture — making fresh food supplementation essential. Supplement with 10 to 30 mg per guinea pig per day; tablets or liquid added to water are unreliable because the vitamin degrades in water and reduces palatability. Timothy hay should be available at all times for digestive health and dental wear. Fresh pellets (limited to about one-eighth cup per guinea pig per day) provide mineral balance. Fresh vegetables should be introduced slowly and one at a time to avoid digestive upset; remove uneaten fresh food within four hours. Avoid iceberg lettuce, potato, rhubarb, and onion. Fresh water in a sipper bottle prevents contamination. Feeding in multiple small portions throughout the day mimics natural grazing behavior and reduces stress.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Bird', 'Parrot and Psittacine Nutrition: Beyond Seeds',
'A seed-only diet is one of the most common causes of nutritional disease in pet parrots and should be avoided as a primary food source. Seeds are high in fat and deficient in vitamin A, calcium, iodine, and amino acids; long-term seed diets lead to hepatic lipidosis, hypovitaminosis A (causing respiratory infections, eye disease, and skin problems), and obesity. A balanced parrot diet should consist primarily of a formulated pellet (60–70% of intake) that provides complete and balanced nutrition, supplemented with fresh vegetables, small amounts of fruit, and limited seeds as treats. Vitamin A-rich foods are particularly important: sweet potato, carrots, leafy greens, and red bell peppers. Dark leafy greens provide calcium and other minerals. Legumes, cooked grains, and small amounts of cooked eggs or lean meat provide protein variety for omnivorous species. Avoid avocado (persin is highly toxic to birds), chocolate, caffeine, onions, and any food with xylitol. Fruit pits and apple seeds contain cyanogenic compounds and should be removed. Salt should be avoided entirely. Many spices including cinnamon, turmeric, and basil are safe and beneficial. Fresh water must be changed daily. Foraging enrichment — hiding food in toys or puzzle feeders — provides mental stimulation and encourages natural feeding behavior.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Snake', 'Feeding Pet Snakes: Prey Size and Frequency',
'Snakes are obligate carnivores that require whole prey items to meet all their nutritional needs. The prey item should be approximately the same width as the widest part of the snake''s body — too large causes regurgitation and potential injury; too small fails to provide adequate nutrition. Frozen-thawed (F/T) prey is strongly preferred over live prey for both safety and hygiene: live prey can injure or kill a snake with bites and scratches, and live feeder rodents may carry parasites and zoonotic diseases. Thaw prey in the refrigerator overnight and warm to body temperature (approximately 37°C) before offering, either in a paper bag with warm water or under a heat lamp; do not microwave, as this causes hot spots. Feeding frequency depends on the snake''s species, age, size, and metabolism. Juvenile snakes typically eat every five to seven days; adults of most species feed every one to two weeks. Arboreal species may feed more frequently. Ball pythons are notorious for extended feeding strikes that can last weeks to months; provide appropriate hide boxes and ensure thermal gradients are correct. Wait 48 hours after feeding before handling to prevent regurgitation. Obesity from overfeeding is common and leads to fatty liver disease; a healthy snake should have a slightly rounded body with no visible spine ridges.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Turtle', 'Aquatic Turtle Nutrition: Diet and Supplementation',
'Aquatic turtles such as red-eared sliders and painted turtles are omnivores whose dietary needs shift with age. Juvenile turtles under two years require a more carnivorous diet — approximately 70% protein sources — to support rapid shell and bone growth. Adult turtles shift toward a more vegetarian diet, with protein comprising about 25 to 50% of intake. Commercial aquatic turtle pellets of high quality provide a balanced base diet; supplement with live, frozen, or freeze-dried aquatic invertebrates (bloodworms, shrimp, snails), leafy greens (romaine, dandelion, kale), and occasional fish. Feeder fish from pet stores frequently carry parasites and vitamin B1-destroying enzymes (thiaminase) and should be used sparingly or avoided. Supplementation with calcium (via cuttlebone floated in water or calcium dusting of food) and vitamin D3 is essential when UVB lighting is inadequate. Fruits are high in sugar and should be an occasional treat only. Avoid iceberg lettuce, spinach in large amounts, and processed human foods. Turtles eat in water; provide a clean, separate feeding tub to reduce contamination of the main enclosure and make portion monitoring easier. Overfeeding promotes shell deformities (pyramiding in tortoises) and obesity that stresses internal organs.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', NULL, 'Reading Pet Food Labels: What to Look For',
'Understanding pet food labels helps owners make informed dietary choices. The AAFCO (Association of American Feed Control Officials) nutritional adequacy statement is the most important item to verify: it should state that the food is "complete and balanced" for the relevant life stage (growth, adult maintenance, all life stages) either by meeting AAFCO profiles or passing feeding trials — feeding trial substantiation is preferable. The ingredient list is ordered by weight before processing; water-heavy ingredients like fresh chicken may appear first but contribute less protein than meat meals after processing. Look for a named protein source (chicken, salmon, lamb) as the first or second ingredient rather than generic "meat" or "poultry." Avoid foods that list corn syrup, artificial colors, or ethoxyquin as a preservative. For dogs and cats, guaranteed analysis provides minimum protein and fat percentages and maximum fiber and moisture; convert to dry matter basis for comparison between wet and dry foods by dividing nutrient percentage by (100 minus moisture%). WSAVA (World Small Animal Veterinary Association) recommends choosing brands that employ board-certified veterinary nutritionists, conduct feeding trials, and publish research. Premium price does not guarantee superior nutrition — boutique, exotic ingredient, or grain-free diets may lack long-term safety data and have been associated with dilated cardiomyopathy in dogs.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Hamster', 'Hamster Nutrition: Seeds, Pellets, and Fresh Foods',
'A well-balanced hamster diet combines commercial hamster pellets or a laboratory block as the nutritional foundation with modest amounts of seeds and fresh foods. Commercial pellets formulated for hamsters provide consistent nutrition and should not be replaced by seed mixes alone, which allow selective feeding of high-fat seeds and lead to nutritional deficiencies. Seed mixes can be offered in small amounts (one teaspoon daily) as enrichment. Fresh foods appropriate for hamsters include small pieces of carrot, broccoli, cucumber, spinach, apple (without seeds), and plain cooked chicken or hard-boiled egg for protein. Introduce fresh foods gradually and in small amounts to avoid digestive upset and diarrhea. Remove uneaten fresh food within four hours to prevent spoilage and bacterial growth in the cage. Syrian (golden) hamsters tend toward diabetes and obesity; limit high-sugar fruits and avoid sweetened treats. Campbell dwarf hamsters are genetically predisposed to diabetes and should have a very low-sugar diet with no fruit. Never feed onion, garlic, raw potato, rhubarb, citrus, or chocolate. Water should be fresh and available at all times via a sipper bottle; check daily that the ball valve is not stuck. A scatter-feeding approach — hiding pellets and seeds in bedding — encourages natural foraging and mental stimulation.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('nutrition', 'Dog', 'Canine Weight Management: Recognizing and Treating Obesity',
'Canine obesity is the most prevalent nutritional disorder in dogs, affecting over 50% of dogs in developed countries. Excess body weight accelerates osteoarthritis, increases risk of diabetes, Cushing''s disease, cardiorespiratory compromise, anesthetic risk, and certain cancers, and reduces life expectancy by up to two years. Body condition scoring on a 9-point scale is the clinical standard: a score of 4–5 is ideal, with ribs easily palpable under a thin fat layer. Scores of 6–7 indicate overweight; 8–9 obese. The primary causes are overfeeding (including excessive treats) and insufficient exercise. Weight loss requires a caloric deficit of approximately 20–30%; the safest approach is transitioning to a veterinary prescription weight management diet that maintains protein to prevent muscle loss while reducing fat and calories. Target loss of 1 to 2% of body weight per week. Monthly weigh-ins track progress. Exercise should be increased gradually, particularly in older dogs or those with orthopedic problems; swimming is excellent for obese dogs with joint disease. All family members must be committed to the plan; "cheating" by one person undermines progress. Once target weight is achieved, transition to a maintenance diet at the new caloric requirement. Keeping a food diary for one week often reveals unexpected sources of excess calories.');

-- ============================================================
-- CATEGORY: vaccination
-- ============================================================

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', 'Dog', 'Core Vaccines for Dogs: Schedule and Importance',
'Core vaccines are recommended for all dogs regardless of lifestyle because the diseases they prevent are severe, widespread, or zoonotic. The canine core vaccines are: distemper virus, adenovirus-2 (hepatitis), parvovirus-2, and rabies. The distemper-adenovirus-parvovirus combination (DAP or DHPP when parainfluenza is included) is given as a series starting at 6 to 8 weeks of age, repeated every 3 to 4 weeks until 16 weeks old, then 12 months later, and every 3 years thereafter per current WSAVA guidelines. Duration of immunity for core vaccines after the puppy series and first adult booster is at least 3 years for most dogs; annual revaccination for core antigens is not recommended by most veterinary organizations. Rabies vaccine is legally required in most jurisdictions; initial vaccination is given at 12 to 16 weeks with a one-year product, followed by a three-year product one year later, then every three years. Non-core vaccines such as Bordetella (kennel cough), leptospirosis, canine influenza, and Lyme disease are recommended based on risk assessment: boarding, grooming, dog parks, and geographic exposure all influence recommendations. Titer testing can assess residual immunity for distemper and parvovirus and may justify deferring booster vaccines in individual dogs.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', 'Cat', 'Core Vaccines for Cats: Schedule and Guidelines',
'The feline core vaccines protect against feline panleukopenia (feline parvovirus), feline herpesvirus-1, and feline calicivirus — collectively given as the FVRCP combination — and rabies. Feline panleukopenia is highly contagious and frequently fatal in unvaccinated cats; it attacks the bone marrow and intestines. Herpesvirus and calicivirus cause upper respiratory disease and are extremely prevalent. The FVRCP series begins at 6 to 8 weeks, repeats every 3 to 4 weeks until 16 weeks, with a booster at one year, then every 3 years for indoor cats with low exposure risk. Some shelter medicine protocols vaccinate from 4 weeks onward. Rabies is required by law in most areas; a one-year product is given at 12 to 16 weeks, then a 3-year product annually and triennially. Feline Leukemia Virus (FeLV) vaccine is recommended as a core vaccine by some organizations for all kittens and as a non-core for cats with outdoor access or FeLV exposure. FeLV causes immunosuppression and lymphoma and is transmitted through prolonged contact with infected cats. Feline Immunodeficiency Virus (FIV) vaccine is available in some countries but has limitations in interfering with FIV testing. Vaccination site selection follows published VAFSTF guidelines to facilitate sarcoma detection and excision if needed.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', 'Rabbit', 'Rabbit Vaccinations: RHDV2 and Myxomatosis',
'Rabbits require vaccination against two serious viral diseases where licensed vaccines are available. Rabbit Hemorrhagic Disease Virus 2 (RHDV2, also called RHD2 or VHD2) is a calicivirus causing acute hemorrhagic disease with very high mortality — up to 90% in unvaccinated rabbits. Infected rabbits may die suddenly with no warning, or show brief fever, bleeding from the nose or mouth, and seizures. The virus is environmentally stable for months, spreads via direct contact, fomites, insects, birds, and contaminated hay, and can travel on clothing and shoes. Vaccination is critical for all rabbits including indoor-only animals given the indirect transmission routes. In countries where the vaccine is available (UK, Europe, Australia), annual vaccination is recommended, though more frequent boosters may be needed in high-risk areas. Myxomatosis, caused by Myxoma virus, is transmitted by fleas, mosquitoes, and mite vectors; it causes severe swelling of the face, genitals, and eyelids and is typically fatal without intensive supportive care. A combined RHDV/myxomatosis vaccine (Nobivac Myxo-RHD Plus) is available in the UK and many European countries, administered from five weeks of age. In the USA, no licensed rabbit vaccines are currently available; discuss unlicensed options with a rabbit-savvy veterinarian if traveling to or from endemic regions.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', 'Dog', 'Leptospirosis Vaccine: Who Needs It and Why',
'Leptospirosis is a bacterial infection caused by Leptospira spirochetes shed in the urine of wildlife including rats, raccoons, skunks, opossums, deer, and cattle. Dogs acquire infection through contact with contaminated water, soil, or urine — swimming in stagnant ponds, walking through puddles, or sniffing infected ground. The disease attacks the kidneys and liver, causing acute kidney injury, liver failure, fever, muscle pain, vomiting, and jaundice; severe cases cause pulmonary hemorrhage syndrome and death. Leptospirosis is also a significant zoonotic disease transmissible to humans. The quadrivalent vaccine (L4) protects against four serovars — Canicola, Icterohaemorrhagiae, Grippotyphosa, and Pomona — and is recommended as a non-core vaccine for dogs with exposure risk. Risk factors include access to natural water bodies, rural or suburban environments with wildlife exposure, hunting or working dog activities, and travel to endemic regions. The initial series requires two doses four weeks apart; annual boosters are required because immunity duration is shorter than for viral vaccines. The vaccine may cause a higher rate of post-vaccination reactions than viral vaccines, particularly in small breeds, but the risk is outweighed by the benefit in endemic areas. Discuss individual risk with your veterinarian.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', NULL, 'Vaccine Side Effects: What to Expect and When to Call the Vet',
'Most pets tolerate vaccines well, and side effects are typically mild and transient. Common normal reactions include mild lethargy, reduced appetite, and soreness at the injection site for 24 to 48 hours. Some pets develop a small, firm lump at the injection site that resolves within 2 to 3 weeks; lumps persisting beyond one month, particularly in cats at common vaccine sites, should be evaluated promptly given the association with vaccine-associated sarcomas in felines. Mild facial swelling, itching around the muzzle, and hives may appear within 30 to 60 minutes in sensitive animals and respond to antihistamines. Veterinary clinics typically observe vaccinated patients for 15 to 30 minutes for this reason. Signs requiring immediate veterinary attention include: severe facial swelling, difficulty breathing, vomiting, pale gums, collapse, or loss of consciousness — these indicate anaphylaxis, a rare but potentially fatal allergic reaction. Persistent or worsening lethargy beyond 48 hours, persistent vomiting, or neurological signs also require evaluation. To reduce reaction risk in animals with a history of vaccine reactions, premedication with diphenhydramine and scheduling vaccines separately rather than combined in one visit are options worth discussing with the veterinarian. Vaccine benefits overwhelmingly outweigh risks in the vast majority of animals. Document all reactions for future visits.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', 'Dog', 'Kennel Cough (Bordetella): Vaccine and Prevention',
'Canine infectious tracheobronchitis, commonly called kennel cough, is a highly contagious upper respiratory syndrome caused most often by Bordetella bronchiseptica in combination with canine parainfluenza virus, adenovirus, or other pathogens. The hallmark sign is a loud, harsh, honking cough that owners sometimes describe as the dog having "something stuck in its throat." Coughing may persist for two to three weeks in otherwise healthy dogs. Complications including pneumonia occur in puppies, immunocompromised dogs, or those with concurrent disease. Transmission occurs through direct contact, shared water bowls, and airborne droplets in enclosed spaces — boarding facilities, groomers, dog parks, training classes, and veterinary waiting rooms all pose exposure risk. The Bordetella vaccine is available as an injectable, intranasal, or oral formulation; the intranasal and oral routes produce local mucosal immunity within 72 hours and may be more effective against respiratory disease than the injectable form. Initial vaccination requires two doses for naive dogs; annual boosters are recommended for at-risk dogs. Many boarding and daycare facilities require proof of Bordetella vaccination. The vaccine reduces severity and duration of illness but does not prevent all infections, as multiple pathogens contribute to the syndrome. Quarantining a coughing dog from other dogs is important to limit spread.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', 'Bird', 'Polyomavirus Vaccine in Psittacines',
'Avian polyomavirus (APV) is a serious infectious disease of psittacine birds, particularly affecting budgerigars and young parrots. In budgerigars, the disease causes French molt, characterized by loss of flight and tail feathers in young birds; in larger psittacines, acute infection in nestlings and recently weaned birds causes sudden death, abdominal distension, delayed crop emptying, and hemorrhage. Survivors can become asymptomatic carriers. Adult birds that survive infection may show no clinical signs but shed virus during periods of stress. A killed virus vaccine is commercially available for psittacines (PsittaciForm polyomavirus vaccine); the primary series consists of two doses three to four weeks apart, administered subcutaneously. Annual boosters are recommended. Vaccination is particularly important in aviaries, breeding facilities, and for newly acquired birds entering an existing collection. PCR testing for APV should be performed before introducing new birds, and new additions should be quarantined for 30 to 45 days. The vaccine does not protect against all psittacine diseases; a comprehensive health program including regular avian veterinary exams, fecal testing for parasites and bacteria, and Chlamydia screening is recommended for breeding collections and pet birds with potential exposure to other birds.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('vaccination', 'Cat', 'FeLV Vaccine: Assessing Risk in Your Cat',
'Feline Leukemia Virus (FeLV) is a retrovirus that integrates into feline DNA, causing progressive immunosuppression, anemia, and lymphoma. Transmission requires prolonged close contact with infected cats — mutual grooming, shared food bowls, bite wounds, and from queen to kittens in utero or through milk. The virus is environmentally fragile and does not survive long outside the cat. Before vaccination, all cats should be tested for existing FeLV infection, as vaccinating a persistently infected cat provides no benefit and may delay diagnosis. ABCD (Advisory Board on Cat Diseases) and AAFP currently recommend FeLV vaccine as a core vaccine for all kittens, as exposure status later in life is unknown. Two doses are given three to four weeks apart starting from eight weeks of age, with a one-year booster, then risk-based reassessment. For adult cats, the vaccine is recommended for those with outdoor access, multi-cat households, or potential exposure to FeLV-positive cats. Currently available vaccines provide 85–100% protection against persistent infection. Injection site selection in the distal limb is recommended by many feline veterinary organizations to facilitate early detection and more complete excision of any injection-site sarcomas. Test and remove FeLV-positive cats from multi-cat households to prevent spread.');

-- ============================================================
-- CATEGORY: emergency
-- ============================================================

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', 'Dog', 'Chocolate Toxicity in Dogs: Dose and Response',
'Chocolate toxicity in dogs is one of the most common calls to veterinary poison hotlines. The toxic compounds are theobromine and caffeine, methylxanthines that dogs metabolize slowly compared to humans. Toxicity is dose-dependent and varies dramatically by chocolate type: white chocolate contains negligible theobromine; milk chocolate contains 44–58 mg/oz; dark chocolate 130–450 mg/oz; baking chocolate up to 390–450 mg/oz; dry cocoa powder up to 800 mg/oz. Clinical signs typically begin 6 to 12 hours after ingestion and include restlessness, vomiting, diarrhea, excessive urination, muscle tremors, increased heart rate, and seizures; cardiac arrhythmias can occur in severe cases. The minimum toxic dose for mild signs is approximately 20 mg/kg; severe signs occur at 40–50 mg/kg; cardiac effects and seizures at 60 mg/kg. If ingestion was recent (within two hours) and the calculated dose is above the mild toxicity threshold, call a veterinarian or ASPCA Poison Control (888-426-4435) immediately. Induced vomiting may be recommended if ingestion was recent; activated charcoal may be given to reduce further absorption. Treatment for symptomatic dogs is supportive: IV fluids, anti-nausea medication, heart rate monitoring, and anticonvulsants. Keep chocolate, cocoa, and hot cocoa products completely inaccessible to dogs.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', 'Dog', 'Gastric Dilatation-Volvulus (GDV): Recognizing Bloat',
'Gastric dilatation-volvulus (GDV), commonly called bloat, is one of the most rapidly fatal emergencies in dogs. The stomach fills with gas (dilatation) and then rotates on its axis (volvulus), trapping contents and cutting off blood supply to the stomach, spleen, and other structures. Without surgical intervention within hours, GDV is fatal. Large, deep-chested breeds are predisposed: Great Danes, German Shepherds, Standard Poodles, Weimaraners, Bloodhounds, Irish Setters, and Boxers have the highest risk. Signs include a visibly distended abdomen, unproductive retching or attempting to vomit without producing anything, excessive salivation, restlessness, pacing, and rapidly progressing collapse. The dog may press its belly against the floor. There is no time to "wait and see." Go immediately to an emergency veterinary facility. Do not induce vomiting. Treatment requires emergency gastric decompression followed by surgery to return the stomach to its normal position and tack it in place (gastropexy) to prevent recurrence. Prophylactic gastropexy at the time of spaying or neutering is strongly recommended for high-risk breeds. Other risk reduction measures include feeding multiple small meals, avoiding exercise for one hour after meals, using elevated bowls only if recommended by the veterinarian, and avoiding diets with high fat content as the first ingredient.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', 'Cat', 'Urethral Obstruction in Male Cats: A True Emergency',
'Urethral obstruction (UO) in male cats is a life-threatening emergency that must be treated within 24 to 48 hours to prevent death from uremia, hyperkalemia-induced cardiac arrest, and bladder rupture. The narrow male urethra becomes blocked by mucus plugs, urinary crystals (most commonly struvite or calcium oxalate), or uroliths. Risk factors include obesity, dry food-only diet, stress, reduced water intake, indoor-only lifestyle, and prior urinary tract disease. Signs include frequent trips to the litter box with little or no urine production, straining and vocalizing in the litter box, restlessness, licking at the genital area, hiding, crying when touched on the abdomen, and eventual collapse and vomiting as uremia worsens. A cat that has been straining to urinate for more than two to three hours without producing urine is an emergency — do not wait. Treatment requires sedation or anesthesia, urinary catheter placement to relieve the obstruction and flush the urethra, fluid therapy to correct dehydration and metabolic derangements, and hospitalization of 24 to 72 hours for monitoring. After unblocking, recurrence rates are up to 50% within two years; prevention includes wet food diet (greatly increases urine output), stress reduction, multicat household management, and prescription urinary diets for cats with crystalluria or recurrent FLUTD.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', NULL, 'Pet Poisoning: First Steps and What NOT to Do',
'Suspected poisoning requires immediate, calm action. First, remove the pet from further exposure to the toxin without endangering yourself. Identify and safely collect the toxin — label, packaging, plant clippings, or a photo on your phone — as this information critically guides treatment. Call your veterinarian or a pet poison control hotline immediately: ASPCA Animal Poison Control Center (888-426-4435, consultation fee applies), or Pet Poison Helpline (855-764-7661, fee applies). Do not induce vomiting unless specifically instructed by a veterinary professional. This is critical — vomiting is contraindicated for caustic substances (bleach, batteries, acids, lye), hydrocarbons, and toxins that cause rapid neurological depression, as it risks aspiration pneumonia or chemical burns to the esophagus. Do not give milk, bread, or home remedies; these do not neutralize toxins and may make the animal worse or complicate treatment. Do not wait for symptoms to develop before seeking guidance — many toxins have delayed clinical effects, and early intervention before signs appear is far more effective. Bring a sample of vomit if the animal has already vomited spontaneously. At the emergency clinic, be prepared to provide the animal''s weight, the substance ingested, the estimated amount, and the time of ingestion. Have your closest 24-hour emergency clinic phone number saved in your phone before an emergency occurs.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', 'Dog', 'Rat Poison (Rodenticide) Toxicity in Dogs',
'Rodenticides are a common and serious cause of poisoning in dogs. The most prevalent type in residential use is anticoagulant rodenticide (first- or second-generation, including brodifacoum, bromadiolone, and diphacinone), which blocks vitamin K-dependent clotting factors, causing uncontrolled internal and external bleeding. Clinical signs appear two to seven days after ingestion, when existing clotting factors are depleted; signs include lethargy, pale gums, difficulty breathing (hemorrhage into the chest cavity), blood in urine or stool, bleeding from the gums, prolonged bleeding from cuts, bruising under the skin, and coughing blood. If ingestion of anticoagulant rodenticide is known or strongly suspected, immediately go to the veterinarian — do not wait for symptoms. If within two hours of ingestion, emesis can be induced and activated charcoal given. Treatment is vitamin K1 supplementation orally for 30 days (not vitamin K3); dogs must be kept quiet to minimize bleeding risk during treatment. Clotting tests (PT, PTT) are performed two days after ending treatment to confirm resolution. Other rodenticide types include bromethalin (neurotoxic, causes cerebral edema — no antidote), zinc phosphide (releases phosphine gas when ingested), and cholecalciferol (vitamin D3, causes fatal hypercalcemia). Identify the specific product to guide treatment.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', NULL, 'Heat Stroke in Pets: Prevention and Emergency Response',
'Heat stroke occurs when a pet''s body temperature rises above 41°C (106°F), overwhelming the body''s ability to dissipate heat and causing cellular damage to multiple organs. In dogs, common scenarios include being left in a parked car (temperature rises to dangerous levels within minutes even on mild days with windows cracked), exercising in hot humid weather, brachycephalic breeds (Bulldogs, Pugs, Boston Terriers, Persian cats) in warm environments, and outdoor pets without shade or water. Signs include rapid, noisy panting, excessive drooling, brick-red or pale gums, disorientation, vomiting, diarrhea, muscle tremors, and collapse. Rectal temperature confirms heat stroke. Emergency first aid: move the pet to a cool, shaded area; apply cool (not ice cold) water to the entire body, particularly the neck, armpits, and groin; use fans to enhance evaporative cooling; offer small amounts of cool water only if conscious and swallowing. Do not use ice water or ice packs directly on the body, as these cause peripheral vasoconstriction that traps heat in the core. Transport immediately to a veterinary facility while continuing cooling in the car with air conditioning. Veterinary treatment involves IV fluid therapy, ongoing temperature monitoring, and treatment of complications including DIC, kidney failure, and cerebral edema. Prevention: never leave pets in parked cars, always provide shade and fresh water, avoid exercise in peak heat hours (10 AM to 4 PM in summer).');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', 'Cat', 'Lily Toxicity in Cats: A Deadly Encounter',
'Lily toxicity is one of the most important feline emergencies for cat owners to be aware of. True lilies of the Lilium genus (Easter lily, tiger lily, stargazer, Asiatic lily, Oriental lily) and Hemerocallis genus (daylilies) are acutely nephrotoxic to cats — the toxic compound has not been fully identified but causes rapid destruction of renal tubular cells. Every part of the plant is toxic, including the pollen (which cats may ingest while grooming) and water in a vase containing lilies. Ingestion of even two or three petals or leaves, a small amount of pollen, or a few drops of vase water can cause fatal acute kidney failure in cats. Clinical signs progress through three stages: initial GI signs (vomiting within 0 to 6 hours), apparent improvement (6 to 24 hours), then acute kidney failure signs including loss of appetite, vomiting, depression, and cessation of urination (24 to 72 hours). Once kidney failure is established, prognosis is grave. If lily ingestion is suspected — even if only the cat was seen near the plant — this is a MEDICAL EMERGENCY. Bring the plant or a photo of it to the clinic. Treatment must begin within 18 hours of ingestion: induced vomiting, activated charcoal, and 48 to 72 hours of aggressive IV fluid therapy to flush the kidneys. Cats that receive prompt treatment before kidney failure establishes have good survival rates. The safest approach: do not keep any Lilium or Hemerocallis species in homes with cats.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', 'Rabbit', 'GI Stasis in Rabbits: Emergency Warning Signs',
'Gastrointestinal stasis is one of the most common and dangerous emergencies in rabbits. The rabbit gut must move constantly — a slowdown or complete stop of gut motility rapidly becomes life-threatening as gas accumulates, gut bacteria overgrow, and the rabbit deteriorates. Unlike dogs and cats, rabbits cannot vomit, making accumulated gas and fermentation products directly damaging. Causes include stress, low fiber intake, pain from dental disease, dehydration, lack of exercise, recent anesthesia, or concurrent illness. Early warning signs include a reduction in fecal output — fewer pellets, smaller pellets, or irregular shapes — and reduced appetite, particularly refusal of favorite foods. As stasis progresses, fecal output stops completely, the abdomen becomes hard and distended, and the rabbit assumes a hunched posture, pressing its belly to the ground. The rabbit may grind its teeth (bruxism) indicating pain, and will feel cold to the touch in severe cases. A rabbit that has not produced fecal pellets for 8 to 12 hours or has not eaten for 12 hours is an emergency — contact a rabbit-savvy veterinarian immediately. Treatment includes gut motility drugs (cisapride, metoclopramide), oral fluid support, pain management, assisted feeding, warmth, and gentle abdominal massage. Avoid withholding food from a rabbit with GI stasis; instead encourage cecotrope consumption and offer high-fiber hay continuously.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('emergency', 'Snake', 'Respiratory Distress in Snakes: When to Act',
'Respiratory infections are among the most common emergencies presenting in snakes and can progress rapidly from mild to fatal, particularly in animals with inadequate husbandry. A snake in respiratory distress will breathe with its mouth open (gaping), produce clicking or wheezing sounds during respiration, hold its head elevated or tilt it back in a "stargazing" position, and may have mucus or fluid visible at the mouth or nares. Excess mucus in the mouth may indicate stomatitis (mouth rot) as a concurrent condition. Causes include bacterial pneumonia (most common), viral infection (IBD in boids), fungal infection (particularly in compromised animals), parasitic infection, or physical obstruction. Predisposing factors include temperatures below the optimal thermal gradient, humidity outside the species-appropriate range, recent stress, and overcrowding. Open-mouth breathing in a snake is always abnormal and warrants same-day veterinary evaluation — do not wait to see if it resolves. A veterinarian will perform a thorough oral exam, take cultures from the trachea, take radiographs to evaluate the lungs, and may collect a blood sample for CBC and chemistry. Treatment typically involves injectable antibiotics (often enrofloxacin combined with a gram-positive antibiotic), nebulization therapy, supportive care, and correction of husbandry deficiencies. Prognosis is good with early treatment; poor with advanced pneumonia involving both lung fields.');

-- ============================================================
-- CATEGORY: post_visit
-- ============================================================

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', NULL, 'Post-Surgery Recovery: General Guidelines',
'Recovery after surgery requires careful attention to cage rest, wound management, and medication compliance. Keep your pet confined to a small, quiet area for the period specified by your veterinarian — this is typically 10 to 14 days for soft tissue surgeries and 6 to 8 weeks for orthopedic procedures. Restriction of activity is critical; excessive movement tears sutures, causes seromas (fluid accumulation), delays healing, and may require a return to the operating room. The Elizabethan collar (e-collar, "cone of shame") must remain on whenever you cannot directly supervise the animal to prevent licking and chewing of the wound. Licking introduces bacteria, dissolves suture material, and can rapidly convert a clean surgical wound to an infected one requiring revision. Check the incision twice daily: redness, swelling, discharge, and gapping or separation of wound edges require same-day veterinary evaluation. A small amount of bruising and mild swelling is normal in the first 48 hours; this should improve daily rather than worsen. Give all medications as directed for the full course, even if the pet appears to be improving. Pain medication should be continued for the prescribed duration — animals that appear comfortable may be masking discomfort. Never give human NSAIDs (ibuprofen, acetaminophen, naproxen) to pets; they cause serious or fatal toxicity. Keep follow-up appointments as scheduled.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', NULL, 'Administering Oral Medication to Pets: Tips and Techniques',
'Medicating pets at home is a common and critical part of veterinary care. For dogs, pilling can be done by placing the pill at the back of the tongue, closing the mouth, and gently stroking the throat until the dog swallows, or by hiding the pill in a small amount of soft food (cream cheese, peanut butter without xylitol, pill pockets, or wet food). Confirm the dog has swallowed the medication and watch for spitting out pills. Liquid medications for dogs can be squirted into the cheek pouch using a syringe. For cats, scruffing and tilting the head back to open the mouth allows pill placement at the back of the tongue; follow with a small amount of water via syringe to ensure the pill reaches the stomach and does not lodge in the esophagus (esophageal stricture from dry pilling is a known complication). Pill guns (pill poppers) reduce the need to put fingers in a cat''s mouth. Compounding pharmacies can formulate many medications as flavored liquids, chewable treats, or transdermal gels for cats that resist oral dosing. Never crush or split medications without confirming it is safe to do so — some sustained-release and enteric-coated medications are dangerous when the matrix is disrupted. Give medications at the same time each day to build routine. Contact the clinic if your pet consistently refuses medication or if the full course cannot be completed.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', NULL, 'Dental Cleaning Aftercare',
'Professional dental cleaning under anesthesia is the gold standard treatment for periodontal disease in companion animals. After the procedure, expect mild lethargy and reduced appetite for 12 to 24 hours due to residual anesthetic effects. If teeth were extracted, soft food should be offered for three to seven days depending on the extent of extractions; your veterinarian will provide specific instructions. If multiple or complex extractions were performed, sutures may be present in the gum tissue — these are typically absorbable and dissolve within two to four weeks. Prevent your pet from chewing on hard toys, bones, or hard kibble until cleared by the veterinarian. Pain medications are usually dispensed for extractions; give all doses as prescribed even if the pet appears comfortable. Antibiotics may be prescribed if pre-existing dental infection was present. Monitor for signs of complications: prolonged refusal to eat beyond 48 hours, pawing at the mouth, swelling of the face or jaw, discharge from extraction sites, or fever. Going forward, daily tooth brushing with pet-specific enzymatic toothpaste is the most effective home dental care method — start slowly and use positive reinforcement. Dental chews, water additives, and dental diets certified by VOHC (Veterinary Oral Health Council) provide benefit when brushing is not achievable. Annual professional cleaning intervals are typically recommended for most pets, though individual variation exists.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', NULL, 'Wound Care at Home: Cleaning and Bandage Changes',
'Proper wound care at home accelerates healing and prevents infection. For minor abrasions and clean lacerations being managed at home, flush the wound gently with sterile saline solution or clean tap water twice daily; do not use hydrogen peroxide (damages healing tissue), betadine at full strength, or alcohol, as these are cytotoxic to the delicate cells that form granulation tissue. For bandaged wounds, your veterinarian will instruct on change frequency; most bandages need replacement every one to three days depending on wound exudate. When removing a bandage, cut along the side and lift gently; if the bandage is stuck to the wound, moisten with saline before peeling. For ongoing home wound care, your veterinarian may prescribe topical antimicrobial cream such as silver sulfadiazine. Signs of wound infection to watch for include increasing redness expanding beyond the wound margins, increasing warmth, malodorous discharge, green or yellow purulent discharge, and worsening pain. A small amount of serous (clear or slightly pink, watery) discharge is normal in early healing; cloudy or discolored discharge is not. Keep the wound site clean and dry between cleaning; prevent the pet from licking using an e-collar. If a drain was placed by the surgeon, do not remove it until instructed; keep the area clean and collect and report the volume of discharge at each bandage change.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', NULL, 'Monitoring Recovery: What Normal and Abnormal Look Like',
'After any veterinary procedure or illness, effective monitoring by the owner is a critical part of recovery. Normal signs in the first 24 to 48 hours after anesthesia or surgery include drowsiness, mild inappetence, and reluctance to engage in normal activities; these should improve daily. Take the pet''s temperature if it appears unwell; fever (above 39.4°C in dogs and cats) may indicate infection or inflammatory response and warrants veterinary contact. Monitor urine output: after an IV fluid infusion during hospitalization, urination may be increased for the first day; absence of urination for more than 24 hours after discharge warrants a call to the clinic. Keep a simple recovery log recording: appetite (percentage of normal amount eaten), water intake, urine and fecal output, activity level, and any medications given and time administered. This information is invaluable when speaking to the veterinary team and helps identify subtle trends. Abnormal signs requiring contact with the clinic include: pale, white, or gray gums; labored or rapid breathing; vomiting or diarrhea persisting beyond 24 hours or containing blood; collapse or extreme weakness; seizures; the incision opening, increasing in redness, or producing discharge; and any behavioral change that concerns you. Your clinic should provide an emergency contact number; do not hesitate to call if you are worried — owners often detect the earliest signs of complications before they become severe.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', 'Dog', 'Spay and Neuter Recovery in Dogs',
'Spaying (ovariohysterectomy) and neutering (orchiectomy) are among the most commonly performed surgeries in dogs. Female dogs typically have a midline abdominal incision four to eight centimeters long; males have a scrotal or prescrotal incision. After discharge, keep the dog quiet and restrict exercise for 10 to 14 days — no running, jumping, playing with other dogs, or use of stairs without assistance. The e-collar must remain on continuously to prevent licking; spay incision licking is the most common complication causing wound breakdown. The incision should be checked twice daily: slight redness and mild swelling in the first three to five days is normal; increasing redness, swelling, discharge, or separation of the incision edges requires same-day evaluation. Internal sutures are typically absorbable; skin closure may be with sutures, staples, or skin glue depending on the surgeon''s preference and will be checked or removed at 10 to 14 days post-operatively. Male dogs that were cryptorchid (undescended testicle) have an abdominal incision and the same activity restrictions apply. Scrotal swelling in recently neutered males may persist for one to two weeks and is often mistaken for a retained testicle; however, if the swelling is hard, warm, or increasing, contact the clinic. Mild lethargy for 24 to 48 hours is expected; the dog should be eating and drinking normally within 24 hours. Pain medication is typically prescribed for three to five days.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', 'Cat', 'Spay and Neuter Recovery in Cats',
'Cats generally recover more quickly than dogs from spay and neuter procedures. Female cats are typically spayed via a flank incision or midline approach; the incision is much smaller than in dogs and suturing may be intradermal (buried stitches with no external suture material visible) or with skin sutures to be removed at 10 to 14 days. Male cats have tiny scrotal incisions that are often left open to heal by secondary intention. Restrict activity for 7 to 10 days for females and three to five days for males; this means no running, jumping, or roughhousing with other pets. The e-collar is essential for females to prevent incision interference — even a brief lick from a cat can start a wound infection. Cats may hide and appear lethargic for 12 to 24 hours post-anesthesia; offer food and water and a quiet safe space. Urination after neuter should occur within 12 to 24 hours; contact the clinic if the cat is straining or has not urinated within that timeframe, particularly in male cats where swelling may contribute to urinary difficulty. Female cats should not be able to conceive immediately but should be kept away from intact males until the incision is fully healed. Post-operative appetite should return within 24 hours; if the cat is not eating by 48 hours post-surgery, contact your veterinarian. The cat may be more affectionate or more withdrawn after surgery — both are normal.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('post_visit', NULL, 'Understanding Your Pet''s Discharge Instructions',
'Written discharge instructions from your veterinary clinic are an essential communication tool and should be read carefully before leaving the clinic and again at home. If anything is unclear — medication dosing, activity restrictions, wound care steps, or follow-up timing — ask for clarification before you leave. Take notes or ask for instructions in writing if the veterinarian explains them verbally. Organize medications before the first dose: read each label, note the frequency, and set phone alarms for consistent timing. Create a simple schedule chart on paper or your phone if multiple medications are prescribed. Note the specific follow-up appointment date and time before leaving, and add it to your calendar immediately. Keep the discharge paperwork in a dedicated folder or take a photo for digital storage; include it when visiting a new veterinarian or emergency clinic. If the patient''s condition changes or worries you at any point during recovery, do not wait until the scheduled follow-up — call the clinic and describe the change. Emergency clinics will ask about post-operative status, current medications, and any known allergies, so having the discharge summary readily accessible is valuable. For exotic species, ask whether your regular clinic can address post-procedure concerns or whether you need the contact of an emergency exotics facility. Follow-up compliance significantly impacts recovery outcomes.');

-- ============================================================
-- CATEGORY: senior_care
-- ============================================================

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', 'Dog', 'Recognizing Aging in Dogs: When Is My Dog a Senior?',
'Dogs age at different rates depending on size and breed. As a general guide, small breeds (under 20 lbs) are considered senior at 10 to 12 years; medium breeds (20–50 lbs) at 8 to 10 years; large breeds (50–90 lbs) at 7 to 8 years; and giant breeds (over 90 lbs) at 5 to 6 years. Giant breeds have shorter lifespans overall and experience age-related health issues sooner. Early signs of aging in dogs include slowing down on walks or reluctance to exercise, difficulty rising after rest (especially on cold mornings), stiffness, hesitation at stairs, reduced hearing and vision, increased sleeping, grey muzzle and face, changes in coat quality, and behavioral changes such as increased anxiety, restlessness at night, or reduced interest in play. Changes in appetite, thirst, urination, or defecation warrant veterinary evaluation at any age but particularly in senior dogs, as they may signal kidney disease, diabetes, Cushing''s disease, or gastrointestinal problems. Semi-annual wellness exams are recommended for senior dogs rather than annual, as medical conditions can progress rapidly and the "biological year" is shorter for older animals. Starting at age seven for small breeds and five for giant breeds, baseline bloodwork and urinalysis establish normal values for individual dogs and allow comparison over time.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', 'Cat', 'Senior Cat Care: Health Changes and Adaptation',
'Cats enter the senior life stage at approximately 10 years of age, and geriatric status at 15 years; many cats live into their late teens or early twenties with appropriate care. Chronic kidney disease is the most common age-related condition, affecting over 30% of cats over 15 years, and progresses silently until over 70% of function is lost; early detection via regular SDMA testing (a sensitive renal biomarker) allows intervention before clinical signs appear. Hyperthyroidism is also prevalent in cats over 10, causing weight loss, increased appetite, restlessness, and hypertension. Dental disease causes chronic pain that may manifest as reduced grooming, changes in eating behavior, or behavioral changes rather than obvious mouth discomfort. Hypertension (high blood pressure), often secondary to kidney disease or hyperthyroidism, can cause sudden blindness from retinal detachment. Arthritis is more common in aging cats than often recognized — cats rarely limp but instead stop jumping, avoid the litter box (if it has high sides), and reduce grooming of their lower back and hindquarters. Environmental adaptations for senior cats include litter boxes with lower entry points, ramps to favorite resting spots, raised food bowls if cervical arthritis is present, and additional litter boxes to reduce travel distance. Soft bedding, warmth, and reduced stress help cats with arthritis. Cognitive dysfunction syndrome — the feline equivalent of dementia — causes vocalization, especially at night, disorientation, and changes in sleep cycles. Nutritional management for senior cats with kidney disease requires reduced phosphorus and protein, which should be implemented under veterinary guidance after diagnosis.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', NULL, 'Joint Health and Arthritis in Aging Pets',
'Osteoarthritis is one of the most prevalent conditions in aging dogs and cats, estimated to affect 80% of dogs over eight years and a large proportion of older cats. The disease involves progressive cartilage degeneration, subchondral bone remodeling, and joint inflammation, causing pain, stiffness, and reduced mobility. In dogs, signs include limping, difficulty rising, reluctance to exercise or play, stiffness after rest that warms up with movement, behavioral changes (increased irritability or withdrawal), and muscle wasting over affected limbs. In cats, signs are more subtle: reduced jumping height, reluctance to use stairs, changes in grooming (especially hindquarters), avoidance of the litter box, and personality changes. Management is multimodal and highly effective when implemented early. Weight management is the single most impactful intervention — reducing body weight by even 10% meaningfully decreases lameness scores. NSAIDs (meloxicam, carprofen, grapiprant, mavacoxib) are the primary pharmaceutical option for dogs; for cats, meloxicam at very low doses is used with monitoring, and several newer feline-specific analgesics including frunevetmab (Solensia, an anti-NGF antibody injection) are now licensed. Omega-3 fatty acids (EPA and DHA from fish oil) have clinical evidence supporting joint benefit. Physical rehabilitation, gentle underwater treadmill exercise, acupuncture, and therapeutic laser therapy provide meaningful additional benefit. Orthopedic beds, ramps, non-slip flooring, and raised food bowls reduce daily strain on arthritic joints.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', 'Dog', 'Canine Cognitive Dysfunction Syndrome',
'Canine Cognitive Dysfunction Syndrome (CDS) is a neurodegenerative disease analogous to Alzheimer''s disease in humans, affecting an estimated 28% of dogs aged 11 to 12 years and rising to over 68% in dogs aged 15 to 16 years. The condition involves accumulation of beta-amyloid plaques and tau proteins, oxidative damage, and neuronal loss. Clinical signs are captured by the DISHAA framework: Disorientation (staring at walls, getting trapped in corners, failure to recognize familiar people or places), altered Interactions (reduced greeting behavior, increased social withdrawal or clinginess), Sleep-wake cycle disturbances (nighttime vocalization, pacing, nocturnal wakefulness), Housetraining accidents, Activity changes (reduced exploration, decreased play, increased aimless activity), and Anxiety (new or worsened fears, separation anxiety, general restlessness). CDS is a diagnosis of exclusion — rule out pain, hypothyroidism, vision and hearing loss, brain tumor, and other medical causes of behavioral change first. Management includes selegiline (Anipryl), the only licensed medication for CDS in dogs; diets enriched with antioxidants and omega-3 fatty acids (Hill''s b/d, Purina ProPlan Bright Mind); environmental enrichment; regular gentle exercise; learning new simple tasks; and keeping routines consistent and predictable. Early recognition and management slow progression and maintain quality of life. Trazodone or melatonin may help with nighttime restlessness.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', NULL, 'Pain Assessment in Senior Pets',
'Pain in senior pets is frequently underrecognized and undertreated because animals instinctively mask pain and cannot verbally communicate it. Owners and veterinarians must rely on behavioral changes, physiological indicators, and validated pain scales. Behavioral signs of chronic pain in dogs include: reduced activity and exercise tolerance, reluctance to jump or use stairs, change in posture (hunched, head held low), reluctance to be touched in painful areas, increased vocalization when moving or handled, changes in facial expression (tense brow, fixed gaze, half-closed eyes — captured in the Canine Grimace Scale), changes in appetite, altered sleep patterns, increased aggression or withdrawal, and cessation of play. In cats, chronic pain signs include reduced grooming of painful areas, overly hunched sitting posture, reduced jumping, facial grimacing (captured in the Feline Grimace Scale), altered social interaction, and house soiling near but not in the litter box. Validated tools for veterinary pain assessment include the Glasgow Composite Measure Pain Scale for acute pain in dogs, the Colorado State University scales, and the Feline Grimace Scale. At home, video recordings of your pet in its normal environment provide invaluable behavioral data that may not be apparent during a clinic visit. If you suspect your senior pet is in pain, do not wait for the next scheduled visit — pain management significantly improves quality of life and is a fundamental component of senior care. Untreated pain accelerates cognitive decline and worsens quality of life.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', 'Cat', 'Chronic Kidney Disease in Cats: Management and Quality of Life',
'Chronic kidney disease (CKD) is the leading cause of death in cats over 10 years. Once diagnosed, staging using the IRIS (International Renal Interest Society) system guides management: Stage 1 (barely detectable, SDMA ≥18 μg/dL or creatinine <1.6 mg/dL), Stage 2 (mild azotemia), Stage 3 (moderate), Stage 4 (severe). Treatment is palliative — CKD is not curable — but quality and length of life can be maintained for months to years with appropriate management. Dietary phosphorus restriction is the most evidenced intervention for slowing progression: veterinary prescription kidney diets (Hills k/d, Royal Canin Renal, Purina NF) reduce phosphorus, protein, and sodium while increasing omega-3 fatty acids. However, cats must eat the diet to benefit; a kidney diet eaten grudgingly or only partially is less beneficial than a non-prescription diet consumed with good appetite. Phosphate binders added to food reduce gut phosphorus absorption when dietary restriction is insufficient. Subcutaneous fluid therapy administered at home by owners provides hydration support in dehydrated or polyuric cats, often improving energy and appetite dramatically; many owners learn this technique and continue it for years. Anti-nausea medications (maropitant, ondansetron) and appetite stimulants (mirtazapine, capromorelin) manage common clinical signs. Hypertension requires amlodipine; proteinuria is managed with benazepril. Regular monitoring every 3 to 6 months tracks disease progression and allows treatment adjustment.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', NULL, 'End-of-Life Care and Quality of Life Assessment',
'End-of-life care is one of the most important and emotionally challenging aspects of pet ownership. The goal of palliative and end-of-life care is to maintain dignity, minimize pain, and maximize quality of life rather than simply extend it. The HHHHHMM scale (Hurt, Hunger, Hydration, Hygiene, Happiness, Mobility, More good days than bad), developed by Dr. Alice Villalobos, provides owners with a structured framework for objective quality-of-life assessment. Each parameter is scored 1 to 10; total scores above 35 typically support a good quality of life; below 35 suggests that palliative measures and consideration of euthanasia are appropriate. Pain must be assessed and controlled throughout the end-of-life period — inadequate pain control in terminal illness is not acceptable. Hospice and palliative care in veterinary medicine includes multimodal analgesia, nutritional support, anti-nausea therapy, wound care, and nursing care. When curative options are exhausted, euthanasia (humane, painless overdose of barbiturate anesthetic) is a final act of care that prevents prolonged suffering. Plan ahead with your veterinarian: discuss the anticipated progression of the disease, what signs will indicate decline, and make a plan for euthanasia before the pet is in crisis — decisions made during acute deterioration are more distressing for families. In-home euthanasia services allow the pet to pass in a familiar, comfortable environment, which many owners find meaningfully reduces distress for the pet and family.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', 'Dog', 'Senior Dog Nutrition: Adapting Diet for the Aging Dog',
'Nutritional needs of dogs change significantly in the senior years, and one-size-fits-all "senior" diets may not be appropriate for all older dogs. Rather than selecting food based solely on age, veterinary guidance considers the individual dog''s body condition, concurrent disease, and specific nutritional needs. Healthy senior dogs without organ disease can continue on a high-quality adult maintenance diet; the key adjustment is caloric reduction if weight gain is occurring, as metabolic rate decreases with age. Protein requirements in healthy senior dogs are the same or slightly higher than adults — protein restriction in elderly dogs without kidney disease leads to muscle wasting. Seniors with chronic kidney disease require phosphorus restriction and moderate protein adjustment per IRIS guidelines, with ongoing monitoring of albumin and body condition. Joint-supportive nutrients — EPA and DHA omega-3 fatty acids from fish oil, glucosamine, and chondroitin — have varying levels of evidence; omega-3 supplementation has the strongest data for joint, cardiovascular, and cognitive benefit. Senior dogs often experience dental pain that affects their ability to eat; soft or moistened food, prescription dental diets, and dental procedures under anesthesia improve comfort and nutrition. Antioxidants (vitamins E and C, beta-carotene, selenium) support immune function and mitochondrial health. Feeding smaller, more frequent meals reduces gastric discomfort and bloat risk in large breed seniors. Always transition diets gradually.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', 'Bird', 'Aging in Parrots: Health Changes and Special Considerations',
'Parrots are among the longest-lived companion animals — large macaws and cockatoos may live 50 to 80 years or more, Amazon parrots and African greys 40 to 60 years, cockatiels 15 to 25 years, and budgerigars 8 to 15 years. Understanding the life stage of the species in your care is important for calibrating health expectations. Senior parrots may develop age-related changes including cataracts and reduced vision, arthritis (particularly in the feet, causing perching difficulty), reproductive disease (egg binding, chronic egg laying, ovarian tumors in females), atherosclerosis (common in African greys and Amazon parrots fed seed-heavy diets), and feather quality changes. Atherosclerosis in psittacines, like in humans, is associated with high-fat diets, sedentary lifestyle, and chronic stress; progression leads to stroke-like episodes, sudden death, or congestive heart failure. Signs in affected birds include exercise intolerance, collapse, and progressive weakness. Liver disease from lipidosis (fat accumulation) is a consequence of long-term seed diets and high-fat treats. Psittacine beak and feather disease (PBFD), a circoviral infection, primarily affects young birds but can manifest in older immunocompromised individuals. Regular avian veterinary exams with CBC, chemistry, and radiographs are particularly important in senior parrots. Environmental enrichment, foraging opportunities, and social interaction maintain cognitive and behavioral health through old age. Heating perches and padded perch covers improve arthritis comfort in aging birds.');

INSERT INTO vet_knowledge (category, pet_type, title, content) VALUES
('senior_care', 'Rabbit', 'Senior Rabbit Care: Health Changes After Age 5',
'Rabbits are considered senior at approximately five to six years of age, though many live to eight or ten years. Health monitoring becomes more important as rabbits age. Uterine cancer is the leading cause of death in unspayed female rabbits; it develops in over 60% of intact females by age five and metastasizes to the lungs and liver. Spaying before age two dramatically reduces this risk and is strongly recommended. Dental disease worsens with age; senior rabbits should receive oral examinations at least twice yearly, and radiographs of the cheek teeth under sedation may be needed if clinical signs such as drooling or weight loss suggest molar spurs. Arthritis in senior rabbits causes reduced grooming of the hindquarters and perineal area, leading to fly strike risk in outdoor rabbits and skin irritation in indoor animals. Assess the rabbit''s ability to groom itself regularly, and provide assistance — trimming fur around the hindquarters, gentle brushing, and keeping bedding clean and dry. Kidney disease and heart disease occur in older rabbits though less commonly than in cats. GI stasis risk increases in senior rabbits and may be triggered by dental pain, arthritis-induced inactivity, or concurrent illness. Provide soft bedding, easy access to the litter box (low entry points), and ensure that hay is always available and fresh. Semi-annual veterinary exams with body weight tracking are recommended from age four onward.');
