apiVersion: v2
name: cert-manager
description: cert-manager with Let's Encrypt DNS-01 wildcard certificates
version: 0.1.0
appVersion: "v1.20.0"
type: application

dependencies:
  - name: cert-manager
    version: "1.20.0"
    repository: https://charts.jetstack.io
