apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-cloud-dns
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: google-cloud-dns-credentials
  data:
    - secretKey: credentials.json
      remoteRef:
        key: secret/dns/google-cloud
        property: credentials
