apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-development
  namespace: traefik
spec:
  secretName: wildcard-development-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.development.cfapps.cool"
    - "development.cfapps.cool"
