apiVersion: v2
name: metallb
description: MetalLB load-balancer for bare-metal Kubernetes clusters
type: application
version: 0.1.0
appVersion: "v0.15.3"

dependencies:
  - name: metallb
    version: "0.15.3"
    repository: https://metallb.github.io/metallb
