apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: grafana-admin-credentials
  data:
    - secretKey: username
      remoteRef:
        key: secret/grafana/admin
        property: username
    - secretKey: password
      remoteRef:
        key: secret/grafana/admin
        property: password
