apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.development.cfapps.cool`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls: {}
