openbao:
  global:
    imagePullSecrets:
      - name: artifact-keeper-pull

  injector:
    enabled: false

  server:
    image:
      registry: artifactory.cfapps.cool
      repository: docker-local/openbao/openbao
      tag: "2.5.1-arm64"
      pullPolicy: IfNotPresent

    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

    dataStorage:
      enabled: true
      size: 10Gi
      storageClass: local-path
      accessMode: ReadWriteOnce

    auditStorage:
      enabled: true
      size: 2Gi
      storageClass: local-path
      accessMode: ReadWriteOnce

    standalone:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address     = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "file" {
          path = "/openbao/data"
        }

    ha:
      enabled: false

    ui:
      enabled: true
      serviceType: ClusterIP
      serviceNodePort: null
