tempo:
  tempo:
    registry: artifactory.cfapps.cool
    repository: docker-local/grafana/tempo
    tag: "2.9.0-arm64"
    pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: artifact-keeper-pull

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    storage:
      trace:
        backend: s3
        s3:
          endpoint: garage.garage.svc:3900
          bucket: tempo-traces
          region: garage
          insecure: true
          forcepathstyle: true
          access_key: GK67013419249d8ea85684b872
          secret_key: 3ebd9aada2a607fded3707c7f4acf8c05bc958cc0a005874606b7efebea6a0ba

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
