tempo:
  tempo:
    registry: artifactory.cfapps.cool
    repository: docker-local/grafana/tempo
    tag: "2.9.0-arm64"
    pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: artifact-keeper-pull

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    storage:
      trace:
        backend: s3
        s3:
          endpoint: garage.garage.svc:3900
          bucket: tempo
          region: garage
          insecure: true
          forcepathstyle: true
          access_key: TEMPO_S3_ACCESS_KEY_PLACEHOLDER
          secret_key: TEMPO_S3_SECRET_KEY_PLACEHOLDER

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
