apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: gitlab-runner-secret
  data:
    - secretKey: runner-token
      remoteRef:
        key: secret/gitlab/runner
        property: token
    - secretKey: runner-registration-token
      remoteRef:
        key: secret/gitlab/runner
        property: token
