apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: marketplace-broker-openbao-token
  namespace: cf-services
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: marketplace-broker-openbao-token
  data:
    - secretKey: token
      remoteRef:
        key: secret/marketplace-broker/openbao-token
        property: token
