apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technitium

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service-ui.yaml
  - service-dns.yaml
  - ingressroute.yaml

commonLabels:
  app.kubernetes.io/name: technitium
  app.kubernetes.io/part-of: platform
  app.kubernetes.io/managed-by: kustomize
