---
# GitLab admin credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-admin-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: gitlab-admin-credentials
  data:
    - secretKey: GITLAB_ROOT_PASSWORD
      remoteRef:
        key: secret/gitlab/admin
        property: root_password
