apiVersion: v1
kind: Service
metadata:
  name: artifact-keeper
  labels:
    app.kubernetes.io/name: artifact-keeper
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: artifact-keeper
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: artifact-keeper
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
