apiVersion: v2
name: traefik
description: Traefik ingress controller for K3s cluster
version: 0.1.0
appVersion: "v3.6.10"
type: application

dependencies:
  - name: traefik
    version: "39.0.5"
    repository: https://traefik.github.io/charts
