apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-admin-s3-credentials
  namespace: garage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: garage-admin-s3-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: secret/garage/admin
        property: access_key
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: secret/garage/admin
        property: secret_key
